<?php
$prod_name=$_POST("txtProductName");
$prod_desc=$_POST("txtProductDesc");
$category=$_POST("txtcategory");
$price=$_POST("txtProductPrice");
$stock_quantity=$_POST("txtProductQty");
$manufacturer=$_POST("txtManufacturer");
$release_date=$_POST("dteReleaseDate");
?>